import Header from "@/components/Header";
import "./globals.css";
import Aside from "@/components/Aside";
import { getCurrentUser } from "@/utils/helperFunctions";
export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <Header user={user} />
        <Aside />
        <main>{children}</main>
      </body>
    </html>
  );
}
